{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bluebox.fullname" . }}-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "bluebox.backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "bluebox.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bluebox.backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "bluebox.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: backend
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.backend.service.targetPort }}
          protocol: TCP
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "bluebox.fullname" . }}-config
              key: DATABASE_URL
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ include "bluebox.fullname" . }}-config
              key: API_HOST
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ include "bluebox.fullname" . }}-config
              key: API_PORT
        livenessProbe:
          {{- toYaml .Values.backend.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.backend.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}
{{- end }}
