{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bluebox.fullname" . }}-frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "bluebox.frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "bluebox.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bluebox.frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "bluebox.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: frontend
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.frontend.service.targetPort }}
          protocol: TCP
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "bluebox.fullname" . }}-config
              key: API_URL
        - name: FRONTEND_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ include "bluebox.fullname" . }}-config
              key: FRONTEND_HOST
        - name: FRONTEND_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ include "bluebox.fullname" . }}-config
              key: FRONTEND_PORT
        livenessProbe:
          {{- toYaml .Values.frontend.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.frontend.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
{{- end }}
