{{- if .Values.ingress.enabled -}}
---
# HTTP to HTTPS redirect for {{ .Values.ingress.host }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "bluebox.fullname" . }}-http-redirect
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "bluebox.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`{{ .Values.ingress.host }}`)
    kind: Rule
    middlewares:
    - name: redirect-to-https
      namespace: traefik
    services:
    - name: noop@internal
      kind: TraefikService
{{- end }}
