apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bluebox.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "bluebox.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
