{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bluebox.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "bluebox.labels" . | nindent 4 }}
{{- end }}
